# Generated by Django 3.0.2 on 2020-03-12 14:32

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('abbreviation', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IMGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('active', models.BooleanField(blank=True, default=False)),
                ('memberGroups', models.ManyToManyField(blank=True, related_name='groups_set', to='identityManager.IMGroup')),
            ],
        ),
        migrations.CreateModel(
            name='IMUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ss', models.CharField(blank=True, max_length=10)),
                ('generated', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name': 'IM User',
                'verbose_name_plural': 'IM Users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='IMUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(blank=True, max_length=25, null=True)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('aboutMe', models.TextField(blank=True, max_length=500, null=True)),
                ('cellularPhone', models.TextField(blank=True, max_length=500, null=True)),
                ('siteUrl', models.URLField(blank=True, max_length=50, null=True)),
                ('company', models.URLField(blank=True, max_length=50, null=True)),
                ('gender', models.NullBooleanField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='identityManager.IMUser')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=60)),
                ('sector', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60)),
                ('title', models.CharField(choices=[('Other', 'Other'), ('SOFTWARE_ENGINEER', 'Software Engineer'), ('SOFTWARE_TEST_ENGINEER', 'Software Test Engineer'), ('SOFTWARE_ARCHITECT', 'Software Architect'), ('SOFTWARE_DEVELOPER', 'Software Developer'), ('BACHELOR_SCIENCE', 'Bachelor of Science (B.S.)')], default=('Other', 'Other'), max_length=50)),
                ('technology', models.TextField(blank=True, max_length=500)),
                ('startDate', models.DateField(null=True)),
                ('finishDate', models.DateField(null=True)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identityManager.IMUserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='IMUserEmailAddresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_username', models.CharField(blank=True, max_length=50, null=True)),
                ('email_password', models.CharField(blank=True, max_length=50, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registered_user_email_addresses', to='identityManager.IMUser')),
            ],
        ),
        migrations.CreateModel(
            name='IMRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('assigned_groups', models.ManyToManyField(blank=True, related_name='roles', to='identityManager.IMGroup')),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='roles', to='identityManager.IMUser')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.Permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'IM Role',
                'verbose_name_plural': 'IM Roles',
            },
        ),
        migrations.AddField(
            model_name='imgroup',
            name='memberUsers',
            field=models.ManyToManyField(blank=True, related_name='groups_set', to='identityManager.IMUser'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(blank=True, max_length=50)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(4.0)])),
                ('startDate', models.DateField(null=True)),
                ('finishDate', models.DateField(null=True)),
                ('activities', models.TextField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_educations', to='identityManager.Degree')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identityManager.IMUserProfile')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schoolin_educations', to='identityManager.School')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('user', models.ManyToManyField(related_name='projects', to='identityManager.IMUser')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='home address', max_length=1024, verbose_name='Full name')),
                ('address1', models.CharField(default='address1', max_length=1024, verbose_name='Address line 1')),
                ('address2', models.CharField(default='address2', max_length=1024, verbose_name='Address line 2')),
                ('zip_code', models.CharField(default='0000', max_length=12, verbose_name='ZIP / Postal code')),
                ('city', models.CharField(default='ankara', max_length=1024, verbose_name='City')),
                ('country', models.CharField(default='turkey', max_length=20, verbose_name='Country')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identityManager.IMUserProfile')),
            ],
            options={
                'verbose_name': 'Shipping Address',
                'verbose_name_plural': 'Shipping Addresses',
            },
        ),
    ]
