# Generated by Django 2.0.4 on 2018-05-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('identityManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.Permission', verbose_name='permissions'),
        ),
    ]
