# Generated by Django 3.0.4 on 2020-04-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identityManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imuser',
            name='dummy',
            field=models.BooleanField(default=False),
        ),
    ]
