# Generated by Django 3.0.2 on 2020-03-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identityManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgroup',
            name='memberGroups',
            field=models.ManyToManyField(blank=True, related_name='groups_set', to='identityManager.IMGroup'),
        ),
        migrations.AlterField(
            model_name='imgroup',
            name='memberUsers',
            field=models.ManyToManyField(blank=True, related_name='groups_set', to='identityManager.IMUser'),
        ),
    ]
