# Generated by Django 2.0.5 on 2018-05-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identityManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imrole',
            name='memberGroups',
        ),
        migrations.RemoveField(
            model_name='imrole',
            name='memberUsers',
        ),
        migrations.AddField(
            model_name='imrole',
            name='asigned_groups',
            field=models.ManyToManyField(blank=True, related_name='assigned_groups', to='identityManager.IMGroup'),
        ),
        migrations.AddField(
            model_name='imrole',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='identityManager.IMUser'),
        ),
    ]
