# Generated by Django 2.0.7 on 2018-07-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identityManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imuser',
            name='generated',
            field=models.BooleanField(default=False),
        ),
    ]
