# Generated by Django 2.0.7 on 2018-07-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identityManager', '0002_imuser_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='turkey', max_length=20, verbose_name='Country'),
        ),
    ]
