# Generated by Django 2.0.5 on 2018-05-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identityManager', '0002_auto_20180509_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imrole',
            old_name='asigned_groups',
            new_name='assigned_groups',
        ),
    ]
