# Generated by Django 2.0.5 on 2018-05-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identityManager', '0003_auto_20180509_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imrole',
            name='assigned_groups',
            field=models.ManyToManyField(blank=True, related_name='roles', to='identityManager.IMGroup'),
        ),
        migrations.AlterField(
            model_name='imrole',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='roles', to='identityManager.IMUser'),
        ),
    ]
