# Generated by Django 3.0.4 on 2020-04-19 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identityManager', '0003_auto_20200418_0357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imuserprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='imuserprofile',
            name='jobTitle',
        ),
        migrations.AlterField(
            model_name='imuseremailaddresses',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registered_user_email_addresses', to='identityManager.IMUserProfile'),
        ),
    ]
