# Generated by Django 3.0.4 on 2020-04-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identityManager', '0004_auto_20200419_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(blank=True, default='address2', max_length=1024, null=True, verbose_name='Address line 2'),
        ),
    ]
