# Generated by Django 2.0.5 on 2018-05-25 02:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identityManager', '0004_auto_20180523_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
