# Generated by Django 2.1.1 on 2018-09-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identityManager', '0004_auto_20180727_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgroup',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='imuser',
            name='generated',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
