# Generated by Django 2.1.1 on 2018-09-29 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identityManager', '0005_auto_20180928_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMUserEmailAddresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_username', models.CharField(blank=True, max_length=50, null=True)),
                ('email_password', models.CharField(blank=True, max_length=50, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_emails', to='identityManager.IMUser')),
            ],
        ),
    ]
