# Generated by Django 3.0.4 on 2020-04-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identityManager', '0006_address_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
