# Generated by Django 2.0.5 on 2018-05-25 02:58

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identityManager', '0006_auto_20180524_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01000000000000000020816681711721685132943093776702880859375')), django.core.validators.MaxValueValidator(Decimal('4'))]),
        ),
    ]
