# Generated by Django 2.1.1 on 2018-09-29 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identityManager', '0006_imuseremailaddresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imuseremailaddresses',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registered_user_email_addresses', to='identityManager.IMUser'),
        ),
    ]
