# Generated by Django 3.0.4 on 2020-04-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identityManager', '0007_workexperience_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='turkey', max_length=30, verbose_name='Country'),
        ),
    ]
