# Generated by Django 3.0.4 on 2020-04-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identityManager', '0009_auto_20200419_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='turkey', max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='school',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
