# Generated by Django 3.0.4 on 2020-04-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identityManager', '0010_auto_20200419_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
